apiVersion: v2
name: common
description: A Helm chart library with some common templates
type: library
version: 0.0.2
annotations:
  artifacthub.io/signKey: |
    fingerprint: FF1E9948F6234DC6D70AB47BF509F29B63C1DC2B
    url: https://shini4i.github.io/charts/pgp_keys.asc
  artifacthub.io/changes: |
    - kind: changed
      description: added chart signing
