configMap:
  # -- resulting ConfigMap name override
  nameOverride: ""
  # -- values of the resulting ConfigMap
  data: {}

podMonitor:
  podMetricsEndpoints: []
  #  - port: metrics
  #  - port: web
  labels: {}

job:
  image:
    repository: curlimages/curl
    tag: 7.85.0
  command: ["curl", "https://ifconfig.me"]
  restartPolicy: Never
  backoffLimit: 1
  annotations:
    "helm.sh/hook": pre-upgrade
  # -- Environment variables to pass to job container
  env: []
  # - name: "ENV_NAME"
  #   value: "test"
  # -- envFrom to pass to job container
  envFrom: []
  # - configMapRef:
  #     name: config-map-name
  # - secretRef:
  #     name: secret-name

keda:
  minReplicaCount: 2
  maxReplicaCount: 5
  triggers: []
    # - metadata:
    #     metricName: app_http_request_count
    #     query: sum(increase(app_http_request_count{path="/important-endpoint"}[2m]))
    #     serverAddress: http://prometheus.monitoring:9090
    #     threshold: '80'
    #     type: prometheus
  fallback: {}
    # failureThreshold: 3
    # replicas: 4
  advanced: {}
    # restoreToOriginalReplicaCount: false
    # horizontalPodAutoscalerConfig:
    #   behavior:
    #     scaleDown:
    #       stabilizationWindowSeconds: 600
    #       policies:
    #         - type: Percent
    #           value: 10
    #           periodSeconds: 15
