apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: {{ include "mongodb-community-cluster.fullname" . }}
  labels:
    {{- include "mongodb-community-cluster.labels" . | nindent 4 }}
spec:
  members: {{ .Values.replicaCount }}
  {{- if .Values.arbiter.enabled }}
  arbiters: {{ .Values.arbiter.replicaCount }}
  {{- end }}
  {{- if .Values.additionalMongodConfig }}
  additionalMongodConfig:
  {{- toYaml .Values.additionalMongodConfig | nindent 4 }}
  {{- end }}
  {{- if .Values.metrics.enabled }}
  prometheus:
    passwordSecretRef:
      name: {{ include "mongodb-community-cluster.fullname" . }}-prometheus-credentials
    username: prometheus
  {{- end }}
  type: {{ .Values.mongod.type }}
  version: {{ .Values.version | default .Chart.AppVersion }}
  security:
    tls:
      enabled: {{ .Values.mongod.tls.enabled }}
      {{- if .Values.mongod.tls.enabled }}
      certificateKeySecretRef:
        name: {{ .Values.mongod.tls.certificateKeySecretRef.name }}
      caConfigMapRef:
        name: {{ .Values.mongod.tls.caConfigMapRef.name }}
      {{- end }}
    authentication:
      modes: ["SCRAM"]
  statefulSet:
    spec:
      template:
        spec:
          containers:
            - name: mongod
              resources:
                {{- toYaml .Values.mongod.resources | nindent 16 }}
            - name: mongodb-agent
              resources:
                {{- toYaml .Values.mongodb_agent.resources | nindent 16 }}
          {{- if .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml .Values.nodeSelector | nindent 12 }}
          {{ end }}
          {{- if .Values.affinity }}
          affinity:
            {{- toYaml .Values.affinity | nindent 12 }}
          {{ end }}
          {{- if .Values.tolerations }}
          tolerations:
            {{- toYaml .Values.tolerations | nindent 12 }}
          {{- end }}
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes:
              {{- .Values.mongod.persistence.data.accessModes | toYaml | nindent 14 }}
            resources:
              requests:
                storage: {{ .Values.mongod.persistence.data.size }}
            {{- if .Values.mongod.persistence.data.storageClassName }}
            storageClassName: {{ .Values.mongod.persistence.data.storageClassName }}
            {{- end }}
        - metadata:
            name: logs-volume
          spec:
            accessModes:
              {{- .Values.mongod.persistence.logs.accessModes | toYaml | nindent 14 }}
            resources:
              requests:
                storage: {{ .Values.mongod.persistence.logs.size }}
            {{- if .Values.mongod.persistence.logs.storageClassName }}
            storageClassName: {{ .Values.mongod.persistence.logs.storageClassName }}
            {{- end }}
  users:
    {{- include "mongodb-users" . | nindent 4 }}
