kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "mongodb-community-cluster.serviceAccountName" . }}-role-binding
  annotations:
    helm.sh/hook: pre-install
    # This hack is required to mitigate ArgoCD PreSync hook mapping to both pre-install and pre-upgrade hooks
    helm.sh/hook-delete-policy: hook-failed
  labels:
    {{- include "mongodb-community-cluster.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "mongodb-community-cluster.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "mongodb-community-cluster.serviceAccountName" . }}-role
  apiGroup: rbac.authorization.k8s.io
