apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "mongodb-community-cluster.serviceAccountName" . }}-role
  annotations:
    helm.sh/hook: pre-install
    # This hack is required to mitigate ArgoCD PreSync hook mapping to both pre-install and pre-upgrade hooks
    helm.sh/hook-delete-policy: hook-failed
  labels:
    {{- include "mongodb-community-cluster.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - create
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - patch
      - delete
      - get
