apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mongodb-community-cluster.serviceAccountName" . }}
  annotations:
    helm.sh/hook: pre-install
    # This hack is required to mitigate ArgoCD PreSync hook mapping to both pre-install and pre-upgrade hooks
    helm.sh/hook-delete-policy: hook-failed
  labels:
    {{- include "mongodb-community-cluster.labels" . | nindent 4 }}
