apiVersion: v2
name: app
description: A Helm chart for a simple app deployment
type: application
version: 0.2.1

annotations:
  artifacthub.io/signKey: |
    fingerprint: FF1E9948F6234DC6D70AB47BF509F29B63C1DC2B
    url: https://shini4i.github.io/charts/pgp_keys.asc
  artifacthub.io/changes: |
    - kind: added
      description: support for argo rollouts-based deployments

maintainers:
  - name: Vadim Gedz
    email: github@shini4i.dev
    url: https://github.com/shini4i

dependencies:
  - name: network-policies
    version: 0.0.6
    repository: https://shini4i.github.io/charts/
