apiVersion: v2
name: app
description: A Helm chart for a simple app deployment
type: application
version: 0.1.0

annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Moved reusable part to `common` chart
    - kind: changed
      description: default image set to `traefik/whoami:v1.8.7`
    - kind: fixed
      description: Condition in `volumeMounts`

maintainers:
  - name: Vadim Gedz
    email: vadims@linux-tech.io
    url: https://github.com/shini4i

dependencies:
  - name: common
    version: v0.0.1
    repository: https://shini4i.github.io/charts
