apiVersion: v2
name: app
description: A Helm chart for a simple app deployment
type: application
version: 0.1.9

annotations:
  artifacthub.io/signKey: |
    fingerprint: FF1E9948F6234DC6D70AB47BF509F29B63C1DC2B
    url: https://shini4i.github.io/charts/pgp_keys.asc
  artifacthub.io/changes: |
    - kind: fixed
      description: move imagePullSecrets in job to a correct yaml level

maintainers:
  - name: Vadim Gedz
    email: vadims@linux-tech.io
    url: https://github.com/shini4i

dependencies:
  - name: common
    version: v0.0.4
    repository: https://shini4i.github.io/charts
  - name: network-policies
    version: 0.0.6
    repository: https://shini4i.github.io/charts/
