apiVersion: v2
name: app
description: A Helm chart for a simple app deployment
type: application
version: 0.0.6

home: https://github.com/shini4i/charts

maintainers:
  - name: Vadim Gedz
    email: vadims@linux-tech.io
