{{- $root := . -}}
{{- range .Values.policies }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $root.Release.Name }}-{{ .name }}
  labels:
    {{- include "network-policies.labels" $root | nindent 4 }}
spec:
  {{- if .podSelector.matchLabels }}
  podSelector:
    matchLabels:
      {{- range $key, $value := .podSelector.matchLabels }}
      {{ $key }}: {{ $value | quote }}
      {{- end }}
  {{- else }}
  podSelector: {}
  {{- end }}
  policyTypes:
    {{- range .policyTypes }}
    - {{ . }}
    {{- end }}
  {{- if .ingress }}
  ingress:
    {{- range .ingress }}
    - from:
      {{- range .from }}
        {{- if .ipBlock }}
        - ipBlock:
            cidr: {{ .ipBlock.cidr }}
            {{- if .ipBlock.except }}
            except:
              {{- range .ipBlock.except }}
              - {{ . }}
              {{- end }}
            {{- end }}
        {{- end }}
        {{- if .namespaceSelector }}
        - namespaceSelector:
            matchLabels:
            {{- range $key, $value := .namespaceSelector.matchLabels }}
              {{ $key }}: {{ $value }}
            {{- end }}
        {{- end }}
        {{- if .podSelector }}
          podSelector:
            matchLabels:
            {{- range $key, $value := .podSelector.matchLabels }}
              {{ $key }}: {{ $value }}
            {{- end }}
        {{- end }}
      {{- if and (not .namespaceSelector) (not .ipBlock) }}
        - podSelector: {}
      {{- end }}
      {{- end }}
      {{- if .ports }}
      ports:
        {{- range .ports }}
        - protocol: {{ .protocol }}
          port: {{ .port }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
  {{- if .egress }}
  egress:
    {{- range .egress }}
    - to:
      {{- range .to }}
        {{- if .ipBlock }}
        - ipBlock:
            cidr: {{ .ipBlock.cidr }}
            {{- if .ipBlock.except }}
            except:
              {{- range .ipBlock.except }}
              - {{ . }}
              {{- end }}
            {{- end }}
        {{- end }}
        {{- if .namespaceSelector }}
        - namespaceSelector:
            matchLabels:
            {{- range $key, $value := .namespaceSelector.matchLabels }}
              {{ $key }}: {{ $value }}
            {{- end }}
        {{- end }}
        {{- if .podSelector }}
          podSelector:
            matchLabels:
            {{- range $key, $value := .podSelector.matchLabels }}
              {{ $key }}: {{ $value }}
            {{- end }}
        {{- end }}
        {{- if and (not .namespaceSelector) (not .ipBlock) }}
          - podSelector: {}
        {{- end }}
      {{- end }}
      {{- if .ports }}
      ports:
        {{- range .ports }}
        - protocol: {{ .protocol }}
          port: {{ .port }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
---
{{- end }}
