{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "argo-watcher.fullname" . }}-deny-ingress
  labels:
    {{- include "argo-watcher.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "argo-watcher.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "argo-watcher.fullname" . }}-allow-self-namespace
  labels:
    {{- include "argo-watcher.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "argo-watcher.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Release.Namespace }}
{{- if .Values.networkPolicies.additionalRules }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "argo-watcher.fullname" . }}-additional-ingress
  labels:
    {{- include "argo-watcher.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "argo-watcher.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    {{- with .Values.networkPolicies.additionalRules }}
    - from:
        {{- toYaml . | nindent 8 }}
      ports:
        - protocol: TCP
          port: {{ $.Values.service.containerPort }}
    {{- end }}
{{- end }}
{{- end }}
