apiVersion: v1
kind: Service
metadata:
  name: {{ include "argo-watcher.fullname" . }}
  labels:
    {{- include "argo-watcher.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.containerPort }}
      protocol: TCP
      name: api
    {{- if .Values.frontend.enabled }}
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.containerPort }}
      protocol: TCP
      name: web
    {{- end }}
  selector:
    {{- include "argo-watcher.selectorLabels" . | nindent 4 }}
