{{- if .Values.healthChecks }}
{{- fail "healthChecks has been removed; use livenessProbe, readinessProbe, and startupProbe instead" }}
{{- end }}
{{- if and (not .Values.postgres.enabled) (gt (int .Values.replicaCount) 1) }}
{{- fail "replicaCount > 1 is not supported with in-memory state (postgres.enabled: false); enable postgres for multi-replica deployments" }}
{{- end }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "argo-watcher.fullname" . }}
  labels:
    {{- include "argo-watcher.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "argo-watcher.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistory }}
  selector:
    matchLabels:
      {{- include "argo-watcher.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "argo-watcher.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "argo-watcher.serviceAccountName" . }}
      {{- if not (kindIs "invalid" .Values.terminationGracePeriodSeconds) }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "argo-watcher.name" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.containerPort }}
              protocol: TCP
          env:
            - name: ARGO_URL
              value: {{ .Values.argo.url }}
            - name: DEPLOYMENT_TIMEOUT
              value: {{ .Values.argo.timeout | quote }}
            - name: ARGO_API_TIMEOUT
              value: {{ .Values.argo.apiTimeout | quote }}
            - name: ARGO_REFRESH_APP
              value: {{ .Values.argo.refreshApp | quote }}
            - name: SKIP_TLS_VERIFY
              value: {{ .Values.argo.skipTlsVerify | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.logLevel | upper }}
            {{- if .Values.updater.sshSecretName }}
            - name: SSH_KEY_PATH
              value: "/tmp/id_rsa"
            - name: SSH_KNOWN_HOSTS
              value: "/tmp/ssh_known_hosts"
            - name: SSH_COMMIT_USER
              value: {{ .Values.updater.commitAuthor }}
            - name: SSH_COMMIT_MAIL
              value: {{ .Values.updater.commitEmail }}
            {{- end }}
            {{- if .Values.argo.urlAlias }}
            - name: ARGO_URL_ALIAS
              value: {{ .Values.argo.urlAlias }}
            {{- end }}
            {{- if .Values.scheduledLockdown }}
            - name: LOCKDOWN_SCHEDULE
              value: {{ include "argo-watcher.scheduleToString" . | quote }}
            {{- end }}
            {{- if .Values.argo.registryProxyUrl }}
            - name: DOCKER_IMAGES_PROXY
              value: {{ .Values.argo.registryProxyUrl }}
            {{- end }}
            - name: STATE_TYPE
              {{- if .Values.postgres.enabled }}
              value: "postgres"
              {{- else }}
              value: "in-memory"
              {{- end }}
            {{- if .Values.postgres.enabled }}
            - name: DB_HOST
              value: {{ .Values.postgres.host }}
            - name: DB_PORT
              value: {{ .Values.postgres.port | quote }}
            - name: DB_NAME
              value: {{ .Values.postgres.name }}
            - name: DB_USER
              value: {{ .Values.postgres.user }}
            {{- if .Values.postgres.secretKey }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.secretName }}
                  key: {{ .Values.postgres.secretKey }}
            {{- end }}
            {{- end }}
            {{- with .Values.extraEnvs }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- $envFrom := list }}
          {{- if .Values.argo.secretName }}
          {{- $envFrom = append $envFrom (dict "secretRef" (dict "name" .Values.argo.secretName)) }}
          {{- end }}
          {{- if and .Values.postgres.enabled (not .Values.postgres.secretKey) }}
          {{- $envFrom = append $envFrom (dict "secretRef" (dict "name" .Values.postgres.secretName)) }}
          {{- end }}
          {{- with $envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.startupProbe.enabled }}
          startupProbe:
            httpGet:
              path: {{ .Values.startupProbe.path }}
              port: http
            periodSeconds: {{ .Values.startupProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.startupProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.startupProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: http
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: http
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.persistence.mountPath }}
            - name: tmp
              mountPath: /tmp
          {{- if .Values.updater.sshSecretName }}
            - name: ssh-key
              mountPath: /tmp/id_rsa
              subPath: {{ .Values.updater.sshKey }}
              readOnly: true
            - name: known-hosts
              mountPath: /tmp/ssh_known_hosts
              subPath: {{ .Values.updater.knownHostsKey }}
              readOnly: true
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: tmp
          emptyDir: {}
      {{- if not .Values.persistence.enabled }}
        - name: data
          emptyDir:
            medium: Memory
            sizeLimit: {{ .Values.persistence.emptyDirSizeLimit }}
      {{- end }}
      {{- if .Values.updater.sshSecretName }}
        - name: ssh-key
          secret:
            secretName: {{ .Values.updater.sshSecretName }}
            items:
              - key: {{ .Values.updater.sshKey }}
                path: {{ .Values.updater.sshKey }}
        - name: known-hosts
          configMap:
            name: {{ .Values.updater.knownHostsConfigMap | default "argo-watcher-ssh-known-hosts" }}
            items:
              - key: {{ .Values.updater.knownHostsKey }}
                path: {{ .Values.updater.knownHostsKey }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
        {{- with .Values.persistence.annotations }}
        annotations:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      spec:
        {{- with .Values.persistence.accessModes }}
        accessModes:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
        {{- if .Values.persistence.storageClassName }}
        storageClassName: {{ .Values.persistence.storageClassName }}
        {{- end }}
  {{- end }}
