{{- include "app.validateValues" . }}
apiVersion: apps/v1
kind: {{ .Values.app.kind }}
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  {{- if and (not .Values.autoscaling.enabled) (not .Values.keda.enabled) }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  {{- if eq .Values.app.kind "Deployment" }}
  strategy:
    type: {{ .Values.app.deployment.strategy }}
    {{- if eq .Values.app.deployment.strategy "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .Values.app.deployment.maxUnavailable }}
      maxSurge: {{ .Values.app.deployment.maxSurge }}
    {{- end }}
  {{- if not (kindIs "invalid" .Values.app.deployment.progressDeadlineSeconds) }}
  progressDeadlineSeconds: {{ .Values.app.deployment.progressDeadlineSeconds }}
  {{- end }}
  {{- else if eq .Values.app.kind "StatefulSet" }}
  serviceName: {{ include "app.statefulSetServiceName" . }}
  podManagementPolicy: {{ .Values.app.statefulSet.podManagementPolicy }}
  updateStrategy:
    type: {{ .Values.app.statefulSet.strategy }}
  {{- end }}
  {{- if not (kindIs "invalid" .Values.app.minReadySeconds) }}
  minReadySeconds: {{ .Values.app.minReadySeconds }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "app.podLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "app.serviceAccountName" . }}
      {{- if not (kindIs "invalid" .Values.app.automountServiceAccountToken) }}
      automountServiceAccountToken: {{ .Values.app.automountServiceAccountToken }}
      {{- end }}
      {{- with .Values.app.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- if not (kindIs "invalid" .Values.app.terminationGracePeriodSeconds) }}
      terminationGracePeriodSeconds: {{ .Values.app.terminationGracePeriodSeconds }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}{{ with .Values.image.tag }}:{{ . }}{{ end }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.app.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.app.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            {{- range .Values.service.ports }}
            - name: {{ .name }}
              containerPort: {{ .containerPort | default .port }}
              protocol: {{ .protocol | default "TCP" }}
            {{- end }}
          {{- $volumeMounts := list }}
          {{- if .Values.app.sharedVolume.enabled }}
          {{- $volumeMounts = append $volumeMounts (dict "mountPath" "/shared" "name" "shared") }}
          {{- end }}
          {{- range .Values.app.additionalVolumeMounts }}
          {{- $volumeMounts = append $volumeMounts . }}
          {{- end }}
          {{- if and (eq .Values.app.kind "StatefulSet") .Values.app.statefulSet.persistence.enabled }}
          {{- range .Values.app.statefulSet.persistence.volumes }}
          {{- $volumeMounts = append $volumeMounts (dict "name" .name "mountPath" .mountPath) }}
          {{- end }}
          {{- end }}
          {{- with $volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.app.lifecycle }}
          lifecycle:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.app.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.app.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.app.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.app.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.app.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- with .Values.sideCars }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- $volumes := list }}
      {{- if .Values.app.sharedVolume.enabled }}
      {{- $volumes = append $volumes (dict "name" "shared" "emptyDir" dict) }}
      {{- end }}
      {{- range .Values.volumes }}
      {{- $volumes = append $volumes . }}
      {{- end }}
      {{- with $volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.app.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if and (eq .Values.app.kind "StatefulSet") .Values.app.statefulSet.persistence.enabled .Values.app.statefulSet.persistence.volumes }}
  volumeClaimTemplates:
    {{- range .Values.app.statefulSet.persistence.volumes }}
    - metadata:
        name: {{ .name }}
      spec:
        accessModes:
          {{- toYaml (.accessModes | default (list "ReadWriteOnce")) | nindent 10 }}
        resources:
          requests:
            storage: {{ .size }}
        {{- if not (kindIs "invalid" .storageClassName) }}
        storageClassName: {{ .storageClassName | quote }}
        {{- end }}
    {{- end }}
  {{- end }}
