{{- if .Values.ingressRoute.enabled -}}
apiVersion: {{ .Values.traefik.apiVersion }}
kind: IngressRoute
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    {{- with .Values.ingressRoute.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.ingressRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
    - {{ .Values.ingressRoute.entryPoint }}
  routes:
    - match: Host(`{{ .Values.ingressRoute.host }}`)
      kind: Rule
      services:
        - name: {{ include "app.fullname" . }}
          port: {{ .Values.ingressRoute.exposedPort }}
      {{- if .Values.middleware.enabled }}
      {{- $middlewares := list }}
      {{- if .Values.middleware.sourceRange }}
      {{- $middlewares = append $middlewares (dict "name" (include "app.suffixedName" (dict "context" $ "suffix" "whitelist"))) }}
      {{- end }}
      {{- range .Values.middleware.existingMiddlewares }}
      {{- $middlewares = append $middlewares (dict "name" .) }}
      {{- end }}
      {{- with $middlewares }}
      middlewares:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
  {{- if .Values.ingressRoute.tls.enabled }}
  tls:
    domains:
      - main: {{ .Values.ingressRoute.host }}
    {{- with .Values.ingressRoute.tlsSecret }}
    secretName: {{ . }}
    {{- end }}
  {{- end }}
{{- end }}
