{{ if .Values.job.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "app.fullname" . }}-job
  {{- if .Values.job.annotations }}
  annotations:
    {{ toYaml .Values.job.annotations }}
  {{- end }}
spec:
  template:
    spec:
      {{- with .Values.job.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.job.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.job.serviceAccountName }}
      serviceAccountName: {{ .Values.job.serviceAccountName }}
      {{- end }}
      {{- if .Values.job.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.job.podSecurityContext | nindent 8 }}
      {{- end }}
      containers:
        - name: job
          image: {{ .Values.job.image.repository }}:{{ .Values.job.image.tag }}
          imagePullPolicy: {{ .Values.job.image.pullPolicy }}
          command:
            {{- range .Values.job.command }}
            - {{ . | quote }}
            {{- end }}
          {{- if .Values.job.env }}
          env:
          {{- toYaml .Values.job.env | nindent 10 }}
          {{- end }}
          {{- if .Values.job.envFrom }}
          envFrom:
          {{- toYaml .Values.job.envFrom | nindent 10 }}
          {{- end }}
          {{- if .Values.job.securityContext }}
          securityContext:
            {{- toYaml .Values.job.securityContext | nindent 12 }}
          {{- end }}
      restartPolicy: {{ .Values.job.restartPolicy }}
      nodeSelector:
        {{-  toYaml .Values.job.nodeSelector | nindent 8 }}
      {{- with .Values.job.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  backoffLimit: {{ .Values.job.backoffLimit }}
{{- end }}
