{{- if .Values.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "app.suffixedName" (dict "context" . "suffix" "metrics") }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    {{- with .Values.podMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
    {{- toYaml .Values.podMonitor.podMetricsEndpoints | nindent 4 }}
{{- end }}
