name: Helm Unit Test

on: pull_request

jobs:
  unittest:
    name: Helm Unit Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout files in the repository
        uses: actions/checkout@v3

      - name: Run unit tests
        uses: d3adb5/helm-unittest-action@v1
