name: Update Readme

on:
  workflow_run:
    workflows:
      - "Release Charts"
    branches: [main]
    types:
      - completed

jobs:
  update-readme:
    name: Update Readme
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - run: pip install -r scripts/requirements.txt
      - run: python scripts/update-readme.py

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs(readme): update images table"
          file_pattern: "README.md"
